### PR TITLE
Huge overhaul and bug fixes

### LINKED ISSUE #6: Crash in MainActivity
It looks like there's a bug in this code in MainActivity:
```
    public void updateBTarmac()
    {
        if(isAuto) {
            bTarmac.setBackgroundColor( (zAutoTarmac == 0) ? darkThemeRed : darkThemeGreen);
            bTarmac.setText(climbDisplayText[zAutoTarmac]);
        }
        else {
            bTarmac.setBackgroundColor( (zTarmac == 0) ? darkThemeRed : darkThemeGreen);
            bTarmac.setText(climbDisplayText[zTarmac]);
        }
    }
```
The problem seems to be that `zAutoTarmac` and `zTarmac` are not always valid indexes for the `climbDisplayText` array. The size of this array is 3, but the index is too large at some point (3).

crash:
```

2024-02-01 20:27:39.967 11498-11498 AndroidRuntime          com.example.a2024frcscoutingapp      E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.a2024frcscoutingapp, PID: 11498
                                                                                                    java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                                    	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:446)
                                                                                                    	at android.view.View.performClick(View.java:5047)
                                                                                                    	at android.view.View$PerformClick.run(View.java:20286)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                    	at android.os.Looper.loop(Looper.java:135)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:5597)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                    	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:441)
                                                                                                    	at android.view.View.performClick(View.java:5047) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:20286) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                    	at android.os.Looper.loop(Looper.java:135) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:5597) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
                                                                                                    Caused by: java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
                                                                                                    	at com.example.a2024frcscoutingapp.MainActivity.updateBTarmac(MainActivity.java:450)
                                                                                                    	at com.example.a2024frcscoutingapp.MainActivity.clickTarmac(MainActivity.java:438)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                                    	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:441) 
                                                                                                    	at android.view.View.performClick(View.java:5047) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:20286) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                    	at android.os.Looper.loop(Looper.java:135) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:5597) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

### PR DESCRIPTION
**Pull request by ipstolen**
changed the number 4 to 3.

### CODE REVIEW

File: app/src/main/java/com/example/a2024frcscoutingapp/MainActivity.java [hunk 1]
```diff
@@ -434,11 +434,11 @@ public void clickMatchPhase(View v){
 
     public void clickTarmac(View v){
         if(isAuto){
-            zAutoTarmac = (zAutoTarmac + 1)%4;
+            zAutoTarmac = (zAutoTarmac + 1)%3;
```
Comment (Krylez) [inline app/src/main/java/com/example/a2024frcscoutingapp/MainActivity.java:437]: looks good.

another option is to use the size of the array so that it never crashes:
```
            zAutoTarmac = (zAutoTarmac + 1)%climbDisplayText.length;
```

**Review by Krylez — APPROVED** [review]

**Comment by Krylez** [comment]
👍

File: app/src/main/java/com/example/a2024frcscoutingapp/MainActivity.java (hunk 1 above)
Comment (ipstolen) [reply app/src/main/java/com/example/a2024frcscoutingapp/MainActivity.java:437]: very smart
